#!/usr/bin/env bash

# move student submission to the source directory
mv /autograder/submission/Submission.hs /autograder/source/Submission.hs

# compile Tests.hs, Submission.hs, and any other necessary files with ghc into executable Tests
ghc /autograder/source/Tests.hs /autograder/source/Submission.hs /autograder/source/TestUtils.hs /autograder/source/ICA3Types.hs /autograder/source/ICA3Shapes.hs -o /autograder/source/Tests

# run the tests and output results to results.json
/autograder/source/Tests > /autograder/results/results.json 2>&1