#!/usr/bin/env bash

# move student submission to the source directory
mv /autograder/submission/Submission.hs /autograder/source/Submission.hs

# compile with ghc
ghc /autograder/source/Tests.hs

# run the tests and output results to results.json
/autograder/source/Tests > /autograder/results/results.json 2>&1